[package]
name = "rustamoz"
version = "0.1.0"
authors = ["Kill KRT"]
edition = "2018"

[lib]
name = "rustamoz_lib"
path = "src/lib.rs"

[[bin]]
name = "rustamoz"
path = "src/main.rs"

[dependencies]
rand = "^0.7.2"
log = "^0.4"
pretty_env_logger = "^0.3"