[package]
name = "rustamoz"
version = "0.1.0"
authors = ["Kill KRT"]
edition = "2018"

[dependencies]
rand = "^0.7.2"
num = "^0.3.1"
serde = { version = "^1.0", features = ["derive"] }
log = "^0.4"
serde_json = "^1.0.59"